#Conversao Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: esdrasnani/conversao-temperatura:1.0.0
        ports:
        - containerPort: 8080

---

#Conversao Service
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

